version: '3'

services:
  todofront:
    image: todofrontend
    container_name: todofront
    depends_on:
      - "todoback"
    environment:
      - REACT_APP_API_HOST=todoback
    ports:
      - 3000:3000
  todoback:
    image: todobackend
    container_name: todoback
    ports:
      - 3001:3001
  todotests:
    image: todotests
    container_name: todotests
    depends_on:
      - "todofront"
      - "todoback"
    environment:
      - FRONT_HOST=todofront
